// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetHealth implements getHealth operation.
//
// Health check endpoint.
//
// GET /healthz
func (UnimplementedHandler) GetHealth(ctx context.Context) (r GetHealthOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRoot implements getRoot operation.
//
// Root endpoint.
//
// GET /
func (UnimplementedHandler) GetRoot(ctx context.Context) (r GetRootOK, _ error) {
	return r, ht.ErrNotImplemented
}

// V1GetHello implements v1GetHello operation.
//
// Sample endpoint with structured response.
//
// GET /v1/hello
func (UnimplementedHandler) V1GetHello(ctx context.Context, params V1GetHelloParams) (r V1GetHelloRes, _ error) {
	return r, ht.ErrNotImplemented
}
