// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetHealthOperation  OperationName = "GetHealth"
	GetRootOperation    OperationName = "GetRoot"
	V1GetHelloOperation OperationName = "V1GetHello"
)
