// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetHealth implements getHealth operation.
	//
	// Health check endpoint.
	//
	// GET /healthz
	GetHealth(ctx context.Context) (GetHealthOK, error)
	// GetRoot implements getRoot operation.
	//
	// Root endpoint.
	//
	// GET /
	GetRoot(ctx context.Context) (GetRootOK, error)
	// V1GetHello implements v1GetHello operation.
	//
	// Sample endpoint with structured response.
	//
	// GET /v1/hello
	V1GetHello(ctx context.Context, params V1GetHelloParams) (V1GetHelloRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
