provider "google" {
  project = var.project_id
  region  = var.project_region
}

provider "google-beta" {
  project = var.project_id
  region  = var.project_region
}

# Locals for dynamic value generation (correct use of locals)
locals {
  # Google Cloud Storage service account (auto-generated by GCP)
  google_storage_sa = "service-${var.project_number}@gs-project-accounts.iam.gserviceaccount.com"

  # ACM allow list with dynamic project ID
  acm_allow_sas = [
    "serviceAccount:terraform@${var.project_id}.iam.gserviceaccount.com"
  ]

  # Monitoring notification channels with dynamic project ID
  monitoring_notification_channels = [
    "projects/${var.project_id}/notificationChannels/${var.monitoring.notification_channel_id}"
  ]
}

# ============================================================================
# NETWORK LAYER
# ============================================================================
module "vpc" {
  source = "../../modules/network/vpc"

  project_region = var.project_region
}

module "access_context_manager" {
  source = "../../modules/network/access_context_manager"

  environment    = var.environment
  project_number = var.project_number
  acm_settings = {
    allow_sas          = local.acm_allow_sas
    company_office_ips = var.acm.company_office_ips
  }
}

module "lb" {
  source = "../../modules/network/lb"

  project_region          = var.project_region
  web_client_domain       = var.web_client_domain
  web_client_bucket_name  = module.gcs.web_client_bucket_name
  api_server_service_name = module.api_server.service_name
  allowed_ip_ranges       = var.acm.company_office_ips
}

# ============================================================================
# DATA LAYER
# ============================================================================

module "secret_manager" {
  source = "../../modules/data/secret-manager"
}

module "alloydb" {
  source = "../../modules/data/alloydb"

  project_region             = var.project_region
  network_id                 = module.vpc.network_id
  alloydb_private_connection = module.vpc.alloydb_private_connection
}

module "gcs" {
  source = "../../modules/data/gcs"

  project_id     = var.project_id
  project_region = var.project_region
  environment    = var.environment
}

module "registry" {
  source = "../../modules/data/registry"

  project_region = var.project_region
}

# ============================================================================
# APP LAYER
# ============================================================================

module "api_server" {
  source = "../../modules/app/api-server"

  project_id      = var.project_id
  project_region  = var.project_region
  network_name    = module.vpc.network_name
  subnetwork_name = module.vpc.subnetwork_name

  db_secrets = {
    db_host     = module.secret_manager.db_host_secret_id
    db_name     = module.secret_manager.db_name_secret_id
    db_password = module.secret_manager.db_password_secret_id
    db_user     = module.secret_manager.db_user_secret_id
  }

  monitoring_license_key_secret_id = module.secret_manager.monitoring_license_key_secret_id
  api_server_settings              = var.api_server
  monitoring_settings_apm = {
    apm = var.monitoring_apm
  }
}

module "worker" {
  source = "../../modules/app/worker"

  project_id      = var.project_id
  project_region  = var.project_region
  network_name    = module.vpc.network_name
  subnetwork_name = module.vpc.subnetwork_name

  db_secrets = {
    db_host     = module.secret_manager.db_host_secret_id
    db_name     = module.secret_manager.db_name_secret_id
    db_password = module.secret_manager.db_password_secret_id
    db_user     = module.secret_manager.db_user_secret_id
  }

  monitoring_license_key_secret_id = module.secret_manager.monitoring_license_key_secret_id

  cloudrun_settings = {
    async_worker = {
      cpu    = var.async_worker.cpu
      memory = var.async_worker.memory
    }
  }

  async_worker_settings = {
    max_scale = var.async_worker.max_scale
    min_scale = var.async_worker.min_scale
  }

  api_server_settings = {
    topic = var.api_server.topic
  }

  monitoring_settings_apm = {
    apm = var.monitoring_apm
  }
}

module "db_migration" {
  source = "../../modules/app/db-migration"

  project_id      = var.project_id
  project_region  = var.project_region
  network_name    = module.vpc.network_name
  subnetwork_name = module.vpc.subnetwork_name

  db_secrets = {
    db_host     = module.secret_manager.db_host_secret_id
    db_name     = module.secret_manager.db_name_secret_id
    db_password = module.secret_manager.db_password_secret_id
    db_user     = module.secret_manager.db_user_secret_id
  }

  cloudrun_settings = {
    db_migration = var.db_migration
  }
}

module "bastion" {
  source = "../../modules/app/bastion"

  project_id       = var.project_id
  project_region   = var.project_region
  network_id       = module.vpc.network_id
  network_name     = module.vpc.network_name
  subnetwork_name  = module.vpc.subnetwork_name
  bastion_settings = var.bastion
}

module "messaging" {
  source = "../../modules/app/messaging"

  project_id              = var.project_id
  project_region          = var.project_region
  project_number          = var.project_number
  csv_upload_bucket_name  = module.gcs.csv_upload_bucket_name
  api_server_service_name = module.api_server.service_name
  api_server_sa_email     = module.api_server.service_account_email
  google_storage_sa       = local.google_storage_sa
}

# ============================================================================
# OPS LAYER
# ============================================================================

module "cloud_build" {
  source = "../../modules/ops/cloud-build"

  project_region      = var.project_region
  github_organization = var.github_organization
  cloudbuild_settings = var.cloud_build
}

module "monitoring" {
  source = "../../modules/ops/monitoring"

  project_id                 = var.project_id
  environment                = var.environment
  monitoring_service_account = var.monitoring_service_account
  monitoring_settings = {
    enabled_alert         = var.monitoring.enabled_alert
    notification_channels = local.monitoring_notification_channels
  }
}
