# https://golangci-lint.run/usage/configuration/#config-file

run:
  timeout: 3m

linters:
  # すべての linter を無効化して、使うものだけ enable で指定する(allow list制)
  # https://golangci-lint.run/usage/linters/
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gci
    - gofmt
    - gocyclo
    - gosec
    - dupl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
